### ISSUE TITLE
dispatch init throws error only on Azure DevOps

### ISSUE THREAD

**Issue by devedse** [microsoft/botbuilder-tools#1457]
## Tool
Name: Dispatch
Version: 1.7.1
OS: Windows server 2019

## Describe the bug
I'm currently creating an Azure DevOps pipeline to automatically create the dispatch model. However when I run the following PowerShell script I keep running into an error that I don't get when I run it locally:

```yaml
- deployment: Deploy_Dispatch_Model
  environment: '${{ parameters.ENVIRONMENT }}'
  pool:
    vmImage: 'windows-2019'
  strategy:
    runOnce:
      deploy:
        steps:
        - task: PowerShell@2
          name: DeployDispatch
          inputs:
            targetType: 'inline'
            errorActionPreference: 'continue'
            script: |
              npm install -g botdispatch

              Write-Host "Running dispatch init..."

              Write-Host "dispatch init -n CHATBOT-${{ parameters.ENVIRONMENT }}-Dispatch --luisAuthoringKey $(LuisAuthoringKey) --luisAuthoringRegion westeurope"
              & dispatch init -n CHATBOT-${{ parameters.ENVIRONMENT }}-Dispatch --luisAuthoringKey $(LuisAuthoringKey) --luisAuthoringRegion westeurope

              Write-Host "File content (Just as a test):"
              Get-Content CHATBOT-DEV-Dispatch.dispatch

              Write-Host "Adding LUIS / QnA models..."

              & dispatch add -t luis -i $(LuisGeneralModelAppId) -n CHATBOT-DEV-General -v $(LuisGeneralModelVersion) -k $(LuisAuthoringKey)
              & dispatch add -t qna -i $(QnAMakerKBId) -n CHATBOT-${{ parameters.ENVIRONMENT }}-KB -k $(QnAMakerKBEndpointKey)
```

This script shows the following logging:
```powershell
"C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'd:\a\_temp\e6aa19d9-d94b-4583-ba7d-a3038400299e.ps1'"
C:\npm\prefix\dispatch -> C:\npm\prefix\node_modules\botdispatch\bin\dispatch.js
+ botdispatch@1.7.1
updated 1 package in 1.456s
Running dispatch init...
dispatch init -n CHATBOT-DEV-Dispatch --luisAuthoringKey 15*********3c --luisAuthoringRegion westeurope
node.exe : CHATBOT-DEV-Dispatch.dispatch created
At C:\npm\prefix\dispatch.ps1:15 char:3
+   & "node$exe"  "$basedir/node_modules/botdispatch/bin/dispatch.js" $ ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (CHATBOT-DEV-Dispatch.dispatch created:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
File content (Just as a test):
{
  "authoringRegion": "westeurope",
  "hierarchical": true,
  "useAllTrainingData": true,
  "dontReviseUtterance": false,
  "copyLuisData": true,
  "normalizeDiacritics": true,
  "services": [],
  "serviceIds": [],
  "authoringKey": "15*********3c",
  "version": "Dispatch",
  "region": "westeurope",
  "type": "dispatch",
  "name": "CHATBOT-DEV-Dispatch"
}
```

Everything seems to work, however this is only because I changed set `errorActionPreference: 'continue'`. If I leave this as default (`Stop`) then the PowerShell script simply exits after the 'RemoteException' message.

As you can see I also added a Write-Host of the exact command that's executed. If I execute that command locally everything works fine:

```powershell
PS C:\XGitDll\dispatchmodel\test2> dispatch init -n CHATBOT-DEV-Dispatch --luisAuthoringKey 15*********3c --luisAuthoringRegion westeurope
CHATBOT-DEV-Dispatch.dispatch created
PS C:\XGitDll\dispatchmodel\test2> $LASTEXITCODE
0
```

I really don't understand how this command can be working flawlessly on my local machine, where it seems to fail on the Azure DevOps environment even though it did create the .dispatch file correctly.

I did also try to run the same script with CMD, but this resulted in a somewhat similar situation where the script failed.

## To Reproduce
Execute the .yml pipeline in Azure DevOps yml pipelines

## Expected behavior
I expect the .dispatch model to be created even when `errorActionPreference` is set to `stop`.

## Screenshots
N/A
![image](https://user-images.githubusercontent.com/2350015/87662105-030b0e00-c762-11ea-91c3-1640c8834009.png)

## Additional context
N/A

[bug]

**Comment by Zerryth** [comment]
@devedse I noticed that you're using PowerShell commands, but in your YAML you specify `script`

```yaml
script: |
             npm install -g botdispatch

              Write-Host "Running dispatch init..."
```
(^ wow spacing is weird copying and pasting 😅 )

Anyways, I think you should switch `script` to be a `powershell`/`pwsh` task, because per [Azure DevOps Services documentation](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#script) when you use `script`, it's a keyword shortcut for cmd.exe on Windows and Bash on other platforms.

And if that's the case PS commands don't necessarily work in cmd:
![image](https://user-images.githubusercontent.com/35248895/87698443-5708f900-c748-11ea-8cdc-5438fb835368.png)

___

Let us know if switching to PS gets you passed that error, and JJ (whom we're having trouble assigning the issue to currently) will help follow-up if that doesn't work

**Comment by devedse** [comment]
Hi @Zerryth, I am using that :), you might have overlooked it, but this is infact a PowerShell task:
```
        - task: PowerShell@2
          name: DeployDispatch
          inputs:
            targetType: 'inline'
            errorActionPreference: 'continue'
            script: |
```
